{% set name = "cobra-component-models" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1722fa0338f47d5b1944f0f7073fa1bbe2a4e175a09077c7440d33989322014f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - depinfo
    - pydantic
    - python >=3.8
    - SQLAlchemy

test:
  imports:
    - cobra_component_models
    - cobra_component_models.orm

about:
  home: https://pypi.org/project/cobra-component-models/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SQLAlchemy ORM and pydantic data models for SQL storage and JSON serialization of COBRA components such as reactions, compounds, and compartments.
  description: |
    Provide SQLAlchemy ORM and pydantic data models for SQL storage and
    serialization of COBRA components such as reactions, compounds, and
    compartments. They are loosely modeled after corresponding classes from the
    [SBML Level 3 Version 2
    specification](http://sbml.org/Documents/Specifications). The data models
    are primarily intended for web services but other applications may benefit
    from these, too.
  doc_url: https://cobra-component-models.readthedocs.io/
  dev_url: https://github.com/opencobra/cobra-component-models

extra:
  recipe-maintainers:
    - Midnighter
